name: ascii_art_tree
description: A minimalistic ASCII Art Tree generator with multiple styles.
version: 1.0.0
repository: https://github.com/gmpassos/ascii_art_tree

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  logging: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^1.0.1
  dependency_validator: ^3.2.2
  test: ^1.21.4
 